//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartender.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cocktail
    {
        public string Name { get; set; }
        public int DrinkID { get; set; }
        public int AlcReqID { get; set; }
        public string Link { get; set; }
        public string Image { get; set; }
    
        public virtual Alcohol Alcohol { get; set; }
    }
}
